#%RAML 1.0 NamedExample 

{ 
   "contactId":2,
   "firstName":"Bob",
   "lastName":"Frederick",
   "dob":06/21/1980,
   "gender":"M",
   "title":"Manager",
   "addressId":1,
   "addressType ":"home",
   "number":1234,
   "street":"blah blah St",
   "unit":"1 a",
   "city":"Somewhere",
   "State":"WV",
   "zipcode":"12345",
   "communicationId":1,
   "communicationType":"email",
   "value":"bfe@sample.com",
   "preferred":"true"
}