#%RAML 1.0 Trait

      headers:
        X-correlation-id:
          type: string
          description: unique id corresponding to each request
        X-session-id:
          type: string
          description: session id corresponding to request.
  